### ISSUE TITLE
Problem when trying to download SSD model endpoint

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/multimodal_movie_analysis#25]
Getting this error @apoman38 
```
analyze_visual|master⚡ ⇒ python3 shot_generator.py -d ~/Downloads/videos                         
Using: cpu
Downloading: "https://github.com/NVIDIA/DeepLearningExamples/archive/torchhub.zip" to /Users/tyiannak/.cache/torch/hub/torchhub.zip
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /Users/tyiannak/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:18<00:00, 5.61MB/s]
Downloading checkpoint from https://api.ngc.nvidia.com/v2/models/nvidia/ssdpyt_fp32/versions/1/files/nvidia_ssdpyt_fp32_20190225.pt
Traceback (most recent call last):
  File "shot_generator.py", line 5, in <module>
    from analyze_visual import *
  File "/Users/tyiannak/Research/libraries/multimodal_movie_analysis/analyze_visual/analyze_visual.py", line 35, in <module>
    generic_model = gmodel.SsdNvidia()
  File "/Users/tyiannak/Research/libraries/multimodal_movie_analysis/analyze_visual/object_detection/generic_model.py", line 64, in __init__
    ckpt_file = _download_checkpoint(checkpoint_str, force_reload=False)
  File "/Users/tyiannak/Research/libraries/multimodal_movie_analysis/analyze_visual/object_detection/generic_model.py", line 17, in _download_checkpoint
    urllib.request.urlretrieve(checkpoint, ckpt_file)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 

```

**Comment by GeorgeTouros** [comment]
I'm getting the same error 
```
Using: cuda:0
Using cache found in /home/zappatistas20/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub
Downloading checkpoint from https://api.ngc.nvidia.com/v2/models/nvidia/ssdpyt_fp32/versions/1/files/nvidia_ssdpyt_fp32_20190225.pth
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/snap/pycharm-professional/218/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/zappatistas20/PycharmProjects/multimodal_movie_analysis/analyze_visual/analyze_visual.py", line 35, in <module>
    generic_model = gmodel.SsdNvidia()
  File "/home/zappatistas20/PycharmProjects/multimodal_movie_analysis/analyze_visual/object_detection/generic_model.py", line 96, in __init__
    ckpt_file = _download_checkpoint(checkpoint_str, force_reload=False)
  File "/home/zappatistas20/PycharmProjects/multimodal_movie_analysis/analyze_visual/object_detection/generic_model.py", line 17, in _download_checkpoint
    urllib.request.urlretrieve(checkpoint, ckpt_file)
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 

```

**Comment by tyiannak** [comment]
@lobracost any ideas??

**Comment by lobracost** [comment]
When accessing Nvidia's api it returns model not found
![image](https://user-images.githubusercontent.com/43955360/100069441-7116be80-2e41-11eb-9311-90c0fb503413.png)

I will try to find out what happened.

**Comment by lobracost** [comment]
@tyiannak @GeorgeTouros I just made a pull request that probably fixes the issue. Please take a look.
