### ISSUE TITLE
TypeError with scikit-image==0.18.0

### ISSUE THREAD

**Issue by theopsall** [tyiannak/multimodal_movie_analysis#31]
With the scikit-image==0.18.0, i get the error :  
Using: cuda:0
Downloading: "https://github.com/NVIDIA/DeepLearningExamples/archive/torchhub.zip" to /home/theo/.cache/torch/hub/torchhub.zip
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/theo/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:02<00:00, 37.3MB/s]
Using cache found in /home/theo/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub
Traceback (most recent call last):
  File "analyze_visual.py", line 35, in <module>
    generic_model = gmodel.SsdNvidia()
  File "/home/theo/Downloads/multimodal_movie_analysis/analyze_visual/object_detection/generic_model.py", line 107, in __init__
    self.utils = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub',
  File "/home/theo/.local/lib/python3.8/site-packages/torch/hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/theo/.local/lib/python3.8/site-packages/torch/hub.py", line 399, in _load_local
    model = entry(*args, **kwargs)
  File "/home/theo/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/hubconf.py", line 230, in nvidia_ssd_processing_utils
    import skimage
  File "/home/theo/.local/lib/python3.8/site-packages/skimage/__init__.py", line 135, in <module>
    from .data import data_dir
  File "/home/theo/.local/lib/python3.8/site-packages/skimage/data/__init__.py", line 156, in <module>
    image_fetcher, data_dir = create_image_fetcher()
  File "/home/theo/.local/lib/python3.8/site-packages/skimage/data/__init__.py", line 136, in create_image_fetcher
    image_fetcher = pooch.create(
TypeError: create() got an unexpected keyword argument 'retry_if_failed'

By the way, with the scikit-image==0.17.2 there is no any error.

**Comment by tyiannak** [comment]
I've updated the requirements file with the scikit-image 0.17.2 requirement until we find this issue.
